// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxcobqgdvfyhupemlvfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Y29icWdkdmZ5aHVwZW1sdmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNTE1MDIsImV4cCI6MjA2MDcyNzUwMn0.PETHYIaTnoW1EtG_pl0VZnpd4-kHRu8ZxBF7SOc8Jo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);